# Generated by Django 3.2.13 on 2022-12-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('message_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('from_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('amount', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=9)),
                ('is_subscription_payment', models.BooleanField(default=False)),
                ('is_first_subscription_payment', models.BooleanField(default=False)),
                ('kofi_transaction_id', models.CharField(max_length=255)),
                ('shop_items', models.TextField(null=True)),
                ('tier_name', models.CharField(max_length=255, null=True)),
                ('shipping', models.TextField(null=True)),
            ],
        ),
    ]
